# Etiquetado de Componentes Conexos

In [1]:
%export QT_DEBUG_PLUGINS=1

UsageError: Line magic function `%export` not found.


In [61]:
import cv2
import numpy as np

In [62]:
imagen = cv2.imread("img/IMG_20191209_100614.jpg", cv2.IMREAD_GRAYSCALE)
_, imagen_bin = cv2.threshold(imagen, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
kernel = np.ones((5,5), np.uint8)

# eliminar ruido
imagen_bin = cv2.morphologyEx(imagen_bin, cv2.MORPH_OPEN, kernel)

# unir partes del mismo tornillo
imagen_bin = cv2.morphologyEx(imagen_bin, cv2.MORPH_CLOSE, kernel)

cv2.imshow("Bin", imagen_bin)
cv2.waitKey(0)


-1

In [63]:
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(imagen_bin, 8, ltype=cv2.CV_32S)
print(f"Etiquetas_n: {num_labels} Etiquetas: {labels} Estadísticos: {stats} Centroides: {centroids}")

Etiquetas_n: 9 Etiquetas: [[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] Estadísticos: [[      0       9    2736    2727 7131331]
 [      0       0    2736     338  294652]
 [   2368      74       8       5      40]
 [    424      92       8       8      64]
 [     58     344       6       7      40]
 [   2724     404      12      24     240]
 [   1552    1161     184     171   18948]
 [    836    1618     177     173   19996]
 [   1595    1793     186     192   20385]] Centroides: [[1369.86343124 1417.89540522]
 [1299.86485074   98.24082307]
 [2371.5          76.        ]
 [ 427.5          95.5       ]
 [  60.625       346.875     ]
 [2730.3         414.3       ]
 [1641.03604602 1245.96838716]
 [ 925.57866573 1704.57276455]
 [1685.05322541 1885.95840078]]


In [64]:
for i in range(1, num_labels):
    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[i]
    if 400 > area > 50:
        cv2.rectangle(imagen, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(imagen, (int(cX), int(cY)), 4, (0, 0, 255), -1)
cv2.imshow('ImagenEtiquetada', imagen)
cv2.waitKey(0)
cv2.destroyAllWindows()

contador = 0
for i in range(1, num_labels):
    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[i]
    if 100 > area > 30:
        contador += 1
        cv2.rectangle(imagen, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(imagen, (int(cX), int(cY)), 4, (0, 0, 255), -1)

print(f"Formas detectadas: {contador}")

Formas detectadas: 3


## De la documentación de OpenCV
### connectedComponentsWithStats
#### Parameters
- image	the 8-bit single-channel image to be labeled
- labels	destination labeled image
- stats	statistics output for each label, including the background label. Statistics are accessed via stats(label, COLUMN) where COLUMN is one of ConnectedComponentsTypes, selecting the statistic. The data type is CV_32S.
- centroids	centroid output for each label, including the background label. Centroids are accessed via centroids(label, 0) for x and centroids(label, 1) for y. The data type CV_64F.
- connectivity	8 or 4 for 8-way or 4-way connectivity respectively
- ltype	output image label type. Currently CV_32S and CV_16U are supported.

---

Los 'stats' están definidos por los siguientes tipos:
- CC_STAT_LEFT 
Python: cv.CC_STAT_LEFT
The leftmost (x) coordinate which is the inclusive start of the bounding box in the horizontal direction.
- CC_STAT_TOP 
Python: cv.CC_STAT_TOP
The topmost (y) coordinate which is the inclusive start of the bounding box in the vertical direction.
- CC_STAT_WIDTH 
Python: cv.CC_STAT_WIDTH
The horizontal size of the bounding box.
- CC_STAT_HEIGHT 
Python: cv.CC_STAT_HEIGHT
The vertical size of the bounding box.
- CC_STAT_AREA 
Python: cv.CC_STAT_AREA
The total area (in pixels) of the connected component.