# Etiquetado de Componentes Conexos

In [31]:
%export QT_DEBUG_PLUGINS=1

UsageError: Line magic function `%export` not found.


In [9]:
import cv2
import numpy as np

In [10]:
imagen = cv2.imread("img/tornillos.jpg", cv2.IMREAD_GRAYSCALE)
_, imagen_bin = cv2.threshold(imagen, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
kernel = np.ones((5,5), np.uint8)

# eliminar ruido
imagen_bin = cv2.morphologyEx(imagen_bin, cv2.MORPH_OPEN, kernel)

# unir partes del mismo tornillo
imagen_bin = cv2.morphologyEx(imagen_bin, cv2.MORPH_CLOSE, kernel)

cv2.imshow("Bin", imagen_bin)
cv2.waitKey(0)

-1

In [11]:
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(imagen_bin, 8, ltype=cv2.CV_32S)
print(f"Etiquetas_n: {num_labels} Etiquetas: {labels} Estadísticos: {stats} Centroides: {centroids}")

Etiquetas_n: 5 Etiquetas: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] Estadísticos: [[    0     0   330   248 69054]
 [  228     7    68   170  4598]
 [   36    88   189   134  8138]
 [  235   101     5     5    25]
 [   42   156     5     5    25]] Centroides: [[162.86945    120.59680829]
 [257.27772945 110.36124402]
 [126.06352912 155.51511428]
 [237.         103.        ]
 [ 44.         158.        ]]


## De la documentación de OpenCV
### connectedComponentsWithStats
#### Parameters
- image	the 8-bit single-channel image to be labeled
- labels	destination labeled image
- stats	statistics output for each label, including the background label. Statistics are accessed via stats(label, COLUMN) where COLUMN is one of ConnectedComponentsTypes, selecting the statistic. The data type is CV_32S.
- centroids	centroid output for each label, including the background label. Centroids are accessed via centroids(label, 0) for x and centroids(label, 1) for y. The data type CV_64F.
- connectivity	8 or 4 for 8-way or 4-way connectivity respectively
- ltype	output image label type. Currently CV_32S and CV_16U are supported.

---

Los 'stats' están definidos por los siguientes tipos:
- CC_STAT_LEFT 
Python: cv.CC_STAT_LEFT
The leftmost (x) coordinate which is the inclusive start of the bounding box in the horizontal direction.
- CC_STAT_TOP 
Python: cv.CC_STAT_TOP
The topmost (y) coordinate which is the inclusive start of the bounding box in the vertical direction.
- CC_STAT_WIDTH 
Python: cv.CC_STAT_WIDTH
The horizontal size of the bounding box.
- CC_STAT_HEIGHT 
Python: cv.CC_STAT_HEIGHT
The vertical size of the bounding box.
- CC_STAT_AREA 
Python: cv.CC_STAT_AREA
The total area (in pixels) of the connected component.

In [12]:
for i in range(1, num_labels):
    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[i]
    if area > 500:
        cv2.rectangle(imagen, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(imagen, (int(cX), int(cY)), 4, (0, 0, 255), -1)
cv2.imshow('ImagenEtiquetada', imagen)
cv2.waitKey(0)
cv2.destroyAllWindows()

contador = 0
for i in range(1, num_labels):
    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[i]
    if area > 500:
        contador += 1
        cv2.rectangle(imagen, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(imagen, (int(cX), int(cY)), 4, (0, 0, 255), -1)

print(f"Formas detectadas: {contador}")

Formas detectadas: 2
