# Etiquetado de Componentes Conexos

In [31]:
%export QT_DEBUG_PLUGINS=1

UsageError: Line magic function `%export` not found.


In [13]:
import cv2
import numpy as np

In [14]:
imagen = cv2.imread("img/tornillos_2.jpg", cv2.IMREAD_GRAYSCALE)
_, imagen_bin = cv2.threshold(imagen, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)
kernel = np.ones((5,5), np.uint8)

# eliminar ruido
imagen_bin = cv2.morphologyEx(imagen_bin, cv2.MORPH_OPEN, kernel)

# unir partes del mismo tornillo
imagen_bin = cv2.morphologyEx(imagen_bin, cv2.MORPH_CLOSE, kernel)

cv2.imshow("Bin", imagen_bin)
cv2.waitKey(0)

-1

In [15]:
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(imagen_bin, 8, ltype=cv2.CV_32S)
print(f"Etiquetas_n: {num_labels} Etiquetas: {labels} Estadísticos: {stats} Centroides: {centroids}")

Etiquetas_n: 31 Etiquetas: [[1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]] Estadísticos: [[     0      0    784    485 317710]
 [     0      0      4      4     15]
 [     0      0     45     32    440]
 [    48     18      6      6     36]
 [    39     29      6      5     30]
 [    54     32    195    188   7904]
 [   426     35     70     62   2243]
 [     3     37     11     19     96]
 [   550     69    187    161   6639]
 [   232     72      6      7     41]
 [   223     85      6      7     40]
 [   483     94     99    139   5087]
 [   213     98      6      6     35]
 [   338    105    136     79   6559]
 [   203    108      7      9     55]
 [   311    174    158    165   7201]
 [     8    205      6      7     41]
 [   120    233    172     57   5337]
 [   243    247      7      8     53]
 [   282    255      5      6     30]
 [     0    262    178    197  14312]
 [   235    298     67    108   3533]
 [ 

## De la documentación de OpenCV
### connectedComponentsWithStats
#### Parameters
- image	the 8-bit single-channel image to be labeled
- labels	destination labeled image
- stats	statistics output for each label, including the background label. Statistics are accessed via stats(label, COLUMN) where COLUMN is one of ConnectedComponentsTypes, selecting the statistic. The data type is CV_32S.
- centroids	centroid output for each label, including the background label. Centroids are accessed via centroids(label, 0) for x and centroids(label, 1) for y. The data type CV_64F.
- connectivity	8 or 4 for 8-way or 4-way connectivity respectively
- ltype	output image label type. Currently CV_32S and CV_16U are supported.

---

Los 'stats' están definidos por los siguientes tipos:
- CC_STAT_LEFT 
Python: cv.CC_STAT_LEFT
The leftmost (x) coordinate which is the inclusive start of the bounding box in the horizontal direction.
- CC_STAT_TOP 
Python: cv.CC_STAT_TOP
The topmost (y) coordinate which is the inclusive start of the bounding box in the vertical direction.
- CC_STAT_WIDTH 
Python: cv.CC_STAT_WIDTH
The horizontal size of the bounding box.
- CC_STAT_HEIGHT 
Python: cv.CC_STAT_HEIGHT
The vertical size of the bounding box.
- CC_STAT_AREA 
Python: cv.CC_STAT_AREA
The total area (in pixels) of the connected component.

In [ ]:
for i in range(1, num_labels):
    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[i]
    if area > 500:
        cv2.rectangle(imagen, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(imagen, (int(cX), int(cY)), 4, (0, 0, 255), -1)
cv2.imshow('ImagenEtiquetada', imagen)
cv2.waitKey(0)
cv2.destroyAllWindows()

contador = 0
for i in range(1, num_labels):
    x = stats[i, cv2.CC_STAT_LEFT]
    y = stats[i, cv2.CC_STAT_TOP]
    w = stats[i, cv2.CC_STAT_WIDTH]
    h = stats[i, cv2.CC_STAT_HEIGHT]
    area = stats[i, cv2.CC_STAT_AREA]
    (cX, cY) = centroids[i]
    if area > 500:
        contador += 1
        cv2.rectangle(imagen, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.circle(imagen, (int(cX), int(cY)), 4, (0, 0, 255), -1)

print(f"Formas detectadas: {contador}")

Formas detectadas: 10
