# Ejemplos transformaciones afines

In [1]:
import cv2
import numpy as np
from transformaciones import TransformacionesEuclideanas, TransformacionesAfines


In [2]:
ruta = "img/form4.png"
imagen = cv2.imread(ruta, cv2.IMREAD_GRAYSCALE)
h,w = imagen.shape

centro_y, centro_x = int(np.floor(h/2)), int(np.floor(w/2))
T1 = TransformacionesEuclideanas.traslado(-centro_x, -centro_y)
print("\n1. Matriz T1 (Traslación al origen):")
print(f"   Traslada la imagen {centro_x} pixels a la izquierda y {centro_y} pixels arriba")
print(T1)
print()
T2 = TransformacionesEuclideanas.traslado(centro_x, centro_y)
print("5. Matriz T2 (Traslación de vuelta al centro):")
print(f"   Traslada la imagen {centro_x} pixels a la derecha y {centro_y} pixels abajo")
print(T2)
print()

RN1 = TransformacionesEuclideanas.rotacion(2,1)
print("2. Matriz RN1 (Rotación):")
print("   Rotación de 2 radianes")
print(RN1)
print()
TN1 = TransformacionesEuclideanas.traslado(0, 0)
print("3. Matriz TN1 (Traslación):")
print("   Traslada 5 pixels en x y 2 pixels en y")
print(TN1)
print()
CN1 = TransformacionesAfines.cizallamiento_vertical(0)
print("4. Matriz CN1 (Cizallamiento vertical):")
print("   Factor de cizallamiento: 0")
print(CN1)
print()
CN2 = TransformacionesAfines.cizallamiento_horizontal(0.2)
print("4. Matriz CN2 (Cizallamiento horizontal):")
print("   Factor de cizallamiento: .2")
print(CN2)
print()
RN2 = TransformacionesEuclideanas.reflexion('y')
print("5. Matriz RN2 (Reflexion):")
print("   Refleja la imagen en el eje y")
print(RN2)
print()
DN1 = TransformacionesAfines.dilatacion_no_uniforme(0.5, 0.5)
print("6. Matriz DN1 (Dilatación):")
print("   Escala la imagen a la mitad en ambos ejes")
print(DN1)

print("="*50)
print("MATRIZ DE TRANSFORMACIÓN COMPUESTA")
print("="*50)
print("\nOrden de multiplicación (de derecha a izquierda):")
print("T = T2 @ RN1 @ TN1 @ T1")
print("\nEsto significa:")
print("1. T1: Traslada al origen")
print("2. RN1: Aplica rotación")
print("3. CN1: Aplica cizallamiento vertical")
print("4. TN1: Aplica traslación")
print("5. T2: Traslada de vuelta al centro original")

T =  CN2 @ DN1 @ RN1 @ RN2 @ T2
print("Matriz de transformación final T (3x3):")
print(T)
print("\n")
print("\nMatriz para OpenCV (2x3) - primeras 2 filas:")
print(T[:2,:])
print()
imagen_procesada = TransformacionesAfines.transformacion_opencv(imagen, T[:2,:], (w,h))



1. Matriz T1 (Traslación al origen):
   Traslada la imagen 125 pixels a la izquierda y 125 pixels arriba
[[   1    0 -125]
 [   0    1 -125]
 [   0    0    1]]

5. Matriz T2 (Traslación de vuelta al centro):
   Traslada la imagen 125 pixels a la derecha y 125 pixels abajo
[[  1   0 125]
 [  0   1 125]
 [  0   0   1]]

2. Matriz RN1 (Rotación):
   Rotación de 2 radianes
[[-0.41614684 -0.90929743  0.        ]
 [ 0.90929743 -0.41614684  0.        ]
 [ 0.          0.          1.        ]]

3. Matriz TN1 (Traslación):
   Traslada 5 pixels en x y 2 pixels en y
[[1 0 0]
 [0 1 0]
 [0 0 1]]

4. Matriz CN1 (Cizallamiento vertical):
   Factor de cizallamiento: 0
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Matriz CN2 (Cizallamiento horizontal):
   Factor de cizallamiento: .2
[[1.  0.2 0. ]
 [0.  1.  0. ]
 [0.  0.  1. ]]

5. Matriz RN2 (Reflexion):
   Refleja la imagen en el eje y
[[ 1  0  0]
 [ 0 -1  0]
 [ 0  0  1]]

6. Matriz DN1 (Dilatación):
   Escala la imagen a la mitad en ambos ejes
[[0.5 0.  

In [3]:
cv2.imshow("Imagen", imagen)
cv2.waitKey(0)

-1

In [4]:
cv2.imshow("ImagenProcesada", imagen_procesada)
cv2.waitKey(0)

-1